server:
  port: 8002
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    batch-service: /batch/** # 将job微服务映射到/batch/**
    user-service: /user/** # 用户中心微服务
    auth-service: /auth/** # 授权中心微服务
  add-host-header: true #添加请求本身的head
  sensitive-headers: #设置敏感头为空，不过滤cookie
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

zzrq:
  jwt:
    cookieName: zzrq_token

zzrq:
  filter:
    allowPaths:
      - /api/auth
      - /api/user