server:
  port: 8083
spring:
  application:
    name: message-service
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /guest

zzrq:
  message:
    accessKeyId: LTAIOgcM7cClXOfZ # 你自己的accessKeyId
    accessKeySecret: RHemWKIkRgUhSPyVPGTOXOwG7uCoEN # 你自己的AccessKeySecret
    signName: zzrq # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称